benefitor:
    resource: "@BenefitorBundle/Resources/config/routing.yml"
    prefix:   /

donor:
    resource: "@DonorBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
